AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
  Exclude:
    - 'spec/**/*'
